# ~/alx_travel_app_0x02/alx_travel_app/listings/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ListingViewSet, BookingViewSet, PaymentInitiationView, PaymentVerificationView

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'listings', ListingViewSet)
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    # The URL patterns generated by the router
    path('', include(router.urls)),
    
    # New custom URL for payment initiation
    path('payments/initiate/', PaymentInitiationView.as_view(), name='payment-initiate'),
    
    # New custom URL for payment verification with a transaction ID
    path('payments/verify/<str:transaction_id>/', PaymentVerificationView.as_view(), name='payment-verify'),
]
